version: '2.1'

services:
  web:
    build:
      context: .
    restart: on-failure
    env_file:
      - docker/dev.env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000


  db:
    image: postgis/postgis:latest
    restart: on-failure
    volumes:
      - /usr/local/var/postgres:/var/lib/postgres/data/pgdata
    env_file:
      - docker/dev.env
