# Generated by Django 3.1.1 on 2020-10-01 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20201001_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='original_id',
        ),
        migrations.AddField(
            model_name='company',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
