# Generated by Django 3.1.1 on 2020-10-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_imported',
            field=models.BooleanField(default=False, verbose_name='Был импортирован?'),
        ),
        migrations.AddField(
            model_name='product',
            name='original_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Исходный ID'),
        ),
    ]
